- name: Install Docker And Run Container
  remote_user: ubuntu
  hosts: all
  tasks:

    - name: Installing Docker
      command: sudo curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    
    - name: Logging into the docker hub account
      command: sudo docker login --username meazmy --password ~7MSim-yutv#6E7

    - name: Running the container
      command: sudo docker run -p 2000:2000 -d meamzy/meazmysampleappcicd:latest