- name: Install Docker And Run Container
  remote_user: ubuntu
  become: yes
  hosts: all
  gather_facts: no # important
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup:
        
    - name: Download Docker
      command: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: Install Docker
      command: sh get-docker.sh

    - name: Logging into the docker hub account
      command: docker login --username '{{ lookup('env', 'DOCKER_USERNAME') }}' --password '{{ lookup('env', 'DOCKER_PASSWORD') }}'
    
    - name: Installing pip
      command: apt-get install python3-pip -y 

    - name: Installing docker-py
      command: pip install docker-py 

    - name: Running the container
      docker_container: 
        name: mycont
        image: "meamzy/meazmysampleappcicd:latest"
        state: started
        ports:
        - "2000:2000"
        - "3306:3306"
